import Sidebar from "~/components/app/nav/Sidebar"
import Topbar from "~/components/app/nav/Topbar"
import { TRPCReactProvider } from "~/trpc/react"
import "~/styles/globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "~/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
  <html lang="en">
    <body 
        className={cn(
        "font-sans antialiased grainy",
        fontSans.variable
       )}>
      <div className="flex min-h-screen w-full flex-col bg-muted/40">
        <Sidebar/> 
        <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
        <Topbar/>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </div>
      </div>
    </body>
  </html>   
  );
}
